name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for reporting an issue. Please remember that I did not create Deadcord. I only copied it from the archive and re-uploaded for everyone to use."
        pr-message: "Thank you for creating a pull-request. Please remember that I did not create Deadcord. I only copied it from the archive and re-uploaded for everyone to use."
